config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  
  resources :user_sessions do
    collection do
      get 'sign_in'
    end
  end
  resources :dashboards
  resources :users, only: [:index] do
    member do
      get 'user_events'
      get 'user_posts'
      get 'user_followers'
    end
  end
  resources :posts, only:[:index]
  resources :events, only:[:index, :show] do
    resources :posts, only:[:destroy] do
      member do
        get 'get_likes'
        get 'get_comments'
        delete 'undo'
      end
      resources :post_comments, only: [:destroy]
    end
  end
  
  resources :categories
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    if params[:page].present?
      page = params[:page]
    else
      page = 1
    end
    request = {
        page:     page,
        per_page: 10
    }
    response_hash = api_request('users', request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @member_profiles  = response.data.member_profiles
      @paging_data      = response.paging_data
    else
      return render json: false
    end
  end
  
  def user_events
    if params[:page].present?
      page = params[:page]
    else
      page = 1
    end
    request = {
        page:     page,
        per_page: 10,
        member_profile_id: params[:id]
    }
    response_hash = api_request('users/user_events', request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @events      = response.data.events
      @paging_data = response.paging_data
    else
      return render json: false
    end
  end

  def user_posts
    if params[:page].present?
      page = params[:page]
    else
      page = 1
    end
    request = {
        page:     page,
        per_page: 10,
        member_profile_id: params[:id]
    }
    response_hash = api_request('users/user_posts', request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @posts       = response.data.posts
      @paging_data = response.paging_data
    else
      return render json: false
    end
  end

  def user_followers
    if params[:page].present?
      page = params[:page]
    else
      page = 1
    end
    request = {
        page:     page,
        per_page: 10,
        member_profile_id: params[:id]
    }
    response_hash = api_request('users/user_followers', request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @followers   = response.data.member_followers
      @paging_data = response.paging_data
    else
      return render json: false
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li><a href="#" class="active">Users</a>

      </li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="example12">
              <thead>
              <tr>
                <th></th>
                <th>Full Name</th>
                <th>Email/Phone</th>
                <th>Events</th>
                <th>Posts</th>
                <th>Followers</th>
                <th>Actions</th>
              </tr>
              </thead>
              <tbody>
                <% @member_profiles.each do |member_profile| %>
                  <tr>
                    <td><i class="fa fa-plus-circle" style="margin-right:10px;"></i></td>
                    <td class="v-align-middle"><%= member_profile[:user][:username]%></td>
                    <td class="v-align-middle"><span class="muted"><%= member_profile[:user][:email] || member_profile[:user][:phone] %></span></td>
                    <td class="v-align-middle"><%= member_profile[:events_count]%></td>
                    <td class="v-align-middle"><%= member_profile[:posts_count]%></td>
                    <td class="v-align-middle"><%= member_profile[:followers_count]%></td>
                    <td class="v-align-middle">delete</td>
                  </tr>
                  <tr class="hidden"><%= render :partial => "shared/user_detail", locals:{member_profile: member_profile} %></tr>
                <% end %>
              </tbody>
            </table>
            <%= render :partial => "shared/pagination" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#example12 tbody td i').live('click', function () {
      var row = $(this).closest('tr').next('tr');
      if ($(this).hasClass('fa fa-plus-circle'))
      {
        $(this).removeClass("fa fa-plus-circle");
        $(this).addClass("fa fa-minus-circle");
        var tr = row.removeClass('hidden');
      }else{
        $(this).removeClass("fa fa-minus-circle");
        $(this).addClass("fa fa-plus-circle");
        var tr = row.addClass('hidden');
      }
    });
  })
</script>

app/views/users/user_events.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li><a href="#" class="active">User Events</a>

      </li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="example12">
              <thead>
              <tr>
                <th></th>
                <th>Event Name</th>
                <th>Start Date</th>
                <th>Finish Date</th>
                <th>Location</th>
                <th>Actions</th>
              </tr>
              </thead>
              <tbody>
              <% @events.each do |event| %>
                  <tr>
                    <td><i class="fa fa-plus-circle" style="margin-right:10px;"></i></td>
                    <td class="v-align-middle"><%= link_to event[:name], event_path(event.id) %></td>
                    <td class="v-align-middle"><span class="muted"><%= event[:start_date] %></span></td>
                    <td class="v-align-middle"><span class="muted"><%= event[:end_date] %></span></td>
                    <td class="v-align-middle"><%= event[:location] %></td>
                    <td class="v-align-middle"><span class="muted">delete</span></td>
                  </tr>
                  <tr class="hidden"><%= render :partial => "shared/event_detail", locals:{event: event} %></tr>
              <% end %>
              </tbody>
            </table>
            <%= render :partial => "shared/pagination" %>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'Go back', users_path, class:'btn btn-default btn-mini' %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#example12 tbody td i').live('click', function () {
      var row = $(this).closest('tr').next('tr');
      if ($(this).hasClass('fa fa-plus-circle'))
      {
        $(this).removeClass("fa fa-plus-circle");
        $(this).addClass("fa fa-minus-circle");
        var tr = row.removeClass('hidden');
      }else{
        $(this).removeClass("fa fa-minus-circle");
        $(this).addClass("fa fa-plus-circle");
        var tr = row.addClass('hidden');
      }
    });
  })
</script>

app/views/users/user_followers.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li><a href="#" class="active">User Followers</a>

      </li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="example12">
              <thead>
              <tr>
                <th>Full Name</th>
                <th>Email/Phone</th>
                <th>status</th>
              </tr>
              </thead>
              <tbody>
              <% @followers.each do |member_follower| %>
                  <tr>
                    <td class="v-align-middle"><%= member_follower[:member_profile][:user][:first_name]%><span class="bold"><%= member_follower[:member_profile][:user][:last_name] %></span></td>
                    <td class="v-align-middle"><span class="muted"><%= member_follower[:member_profile][:user][:email] || member_follower[:member_profile][:user][:phone] %></span></td>
                    <td class="v-align-middle"><%= member_follower[:following_status] %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <%= render :partial => "shared/pagination" %>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'Go back', users_path, class:'btn btn-default btn-mini' %>
  </div>
</div>

app/views/users/user_posts.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li><a href="#" class="active">User Posts</a>

      </li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="example12">
              <thead>
              <tr>
                <th></th>
                <th>Post Title</th>
                <th>Created By</th>
                <!--<th>Is public</th>-->
                <th>Likes count</th>
                <th>Comments count</th>
                <th>Actions</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <% @posts.each do |post| %>
                  <tr>
                    <td><i class="fa fa-plus-circle" style="margin-right:10px;"></i></td>
                    <td class="v-align-middle"><%= link_to post[:post_title], posts_path(post.id)  %></td>
                    <td class="v-align-middle"><%=link_to "#{post[:member_profile][:user][:username]}", '#' %></td>
                    <!--<td class="v-align-middle"><span class="muted"><!%= post[:is_post_public] %></span></td>-->
                    <td class="v-align-middle"><%= post[:likes_count] %></td>
                    <td class="v-align-middle"><%= post[:comments_count] %></td>
                    <td class="v-align-middle">
                      <% if post.is_deleted %>
                          <!--%= link_to 'Undo', undo_event_post_path(post.event_id, post.id) , class: 'btn btn-warning btn-mini', data: { confirm: 'Are you sure to undo?' }, method: 'delete' %-->
                      <% else %>
                          <!--%= link_to 'delete', event_post_path(post.event_id, post.id), class: 'btn btn-danger btn-mini', data: { confirm: 'Are you sure to delete this post?' }, method: 'delete' %-->
                      <% end %>
                    </td>
                  </tr>
                  <tr class="hidden"><%= render :partial => "shared/post_detail", locals:{post: post, event_id: post.event_id} %></tr>
              <% end %>
              </tbody>
            </table>
            <%= render :partial => "shared/pagination" %>
          </div>
        </div>
      </div>
    </div>
    <% if @event_id.present? %>
      <%= link_to 'Go back', events_path, class:'btn btn-default btn-mini' %>
    <% else %>
        <%= link_to 'Go back', users_path, class:'btn btn-default btn-mini' %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#example12 tbody td i').live('click', function () {
      var row = $(this).closest('tr').next('tr');
      if ($(this).hasClass('fa fa-plus-circle'))
      {
        $(this).removeClass("fa fa-plus-circle");
        $(this).addClass("fa fa-minus-circle");
        var tr = row.removeClass('hidden');
      }else{
        $(this).removeClass("fa fa-minus-circle");
        $(this).addClass("fa fa-plus-circle");
        var tr = row.addClass('hidden');
      }
    });
  })
</script>