config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  
  resources :user_sessions do
    collection do
      get 'sign_in'
    end
  end
  resources :dashboards
  resources :users, only: [:index] do
    member do
      get 'user_events'
      get 'user_posts'
      get 'user_followers'
    end
  end
  resources :posts, only:[:index]
  resources :events, only:[:index, :show] do
    resources :posts, only:[:destroy] do
      member do
        get 'get_likes'
        get 'get_comments'
        delete 'undo'
      end
      resources :post_comments, only: [:destroy]
    end
  end
  
  resources :categories
  
end

app/views/shared/_comment_detail.html.erb
<td class="details" colspan="6" style="background-color: lavender;">
  <div class="row">
    <div class="col-md-12">
      <h3>Post Comment</h3>
      <p><%= comment[:post_comment]%></p>
    </div>
  </div>
</td>

app/views/shared/_event_detail.html.erb
<td class="details" colspan="6" style="background-color: lavender;">
  <div class="row">
    <div class="col-md-6">
      <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table">
        <tbody>
        <tr>
          <td><b>Category:</b></td>
          <!--<td><!%= event[:category].present? ? event[:category][:name] : '' %></td>-->
        </tr>
        <tr>
          <td><b>#tags:</b></td>
          <!--<td>-->
            <!--<!% event[:hashtags] && event[:hashtags].each do |tag| %>-->
                <!--<span><!%= tag[:name] + ',' %></span>-->
            <!--<!% end %>-->
          <!--</td>-->
        </tr>
        <tr>
          <td><b>Event Members:</b></td>
          <!--<td>-->
            <!--<!% event[:event_members] && event[:event_members].each do |member| %>-->
                <!--<span><!%= member[:member_profile][:user][:username]%></span>-->
            <!--<!% end %>-->
          <!--</td>-->
        </tr>
        <tr>
          <td><b>Co Host:</b></td>
          <!--<td>-->
            <!--<!% event[:event_co_hosts] && event[:event_co_hosts].each do |member| %>-->
                <!--<span><!%= member[:member_profile][:user][:username]%></span>-->
            <!--<!% end %>-->
          <!--</td>-->
        </tr>
        <tr>
          <td></td>
          <!--<td><!%= event[:message_from_host]%></td>-->
        </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table table table-striped">
        <tbody>
        <tr>
          <td><b>#of posts</b></td>
          <!--<td><!%= event[:post_count] %></td>-->
          <!--<td>-->
            <!--<!% if event[:post_count] > 0 %>-->
                <!--<!%= link_to 'view posts', event_path(event[:id]) %>-->
            <!--<!% end %>-->
          <!--</td>-->
        </tr>
        </tbody>
      </table>
      <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table table table-striped">
        <thead>
        <th>Attachment Type</th>
        <th>Action</th>
        </thead>
        <!--<tbody>-->
        <!--<!% event[:event_attachments] && event[:event_attachments].each do |attachment| %>-->
            <!--<tr>-->
              <!--<td><!%= attachment[:attachment_type] %></td>-->
              <!--<td><!%= link_to 'view file', attachment[:attachment_url], target: '_blank'%></td>-->
            <!--</tr>-->
        <!--<!% end %>-->
        <!--</tbody>-->
      </table>
    </div>
  </div>
</td>

app/views/shared/_pagination.html.erb
<script>

  $(document).ready(function() {
    html = '';
    path_name = window.location.pathname;
    var page        = parseInt($("#page").text());
    var total_pages = parseInt($("#total_pages").text());
    if (page >= 1 && page <= 10)
    {
      html += '<span> << previous</span>';
      html += ' ';
      for(i=1;i<=10;i++)
      {

        if (i == page)
        {
          html += '<span>' + i + '</span>';
          html += ' ';
        }
        else if (i <= total_pages)
        {
          html += '<a href='+ path_name +'?page=' + i + '>' + i + '</a>';
          html += ' ';
        }

      }
      if (total_pages > 10 )
      {
        html += '<a href='+ path_name +'?page=' + i + '> Next >> </a>';
      }
      else
      {
        html += '<span> Next >> </span>';
      }
    }
    else
    {
      start_page    = page - 5;
      end_page      = page + 5;
      previous_page = start_page - 1;
      html += '<a href='+ path_name +'?page=' + previous_page + '> << previous</a>';
      html += ' ';

      for (i=start_page;i<= end_page; i++)
      {
        if (i == page)
        {
          html += '<span>' + i + '</span>';
          html += ' ';
        }
        else if (i <= total_pages)
        {
          html += '<a href='+ path_name +'?page=' + i + '>' + i + '</a>';
          html += ' ';
        }
      }
      if (total_pages > end_page )
      {
        html += '<a href='+ path_name +'?page=' + i + '> Next >> </a>';
      }
      else
      {
        html += '<span> Next >> </span>';
      }
    }

    $("#pagination").append(html);
  });

</script>
<div id="pagination" class='pull-right'>
  <span class="hidden" id="page">
    <%= "#{@paging_data[:page]}" %>
  </span>
  <span class="hidden" id="total_pages">
    <%= "#{@paging_data[:total_pages]}" %>
  </span>
</div>

app/views/shared/_post_detail.html.erb
<td class="details" colspan="6" style="background-color: lavender;">
  <div class="row">
    <div class="col-md-6">
      <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table">
        <tbody>
        <tr>
          <td><b>Created By:</b></td>
          <td><%= post[:member_profile][:user][:username] %></td>
        </tr>
        <tr>
          <td><b>Event:</b></td>
          <td><!--%= post[:event][:name] %--></td>
        </tr>
        <tr>
          <td><b>Post Members:</b></td>
          <td>
            <% post[:post_members] && post[:post_members].each do |member| %>
                <span><%= member[:member_profile][:user][:username]%></span>
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <% if post[:likes_count] > 0 || post[:comments_count] > 0%>
        <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table table table-striped">
          <tbody>
          <tr>
            <td>
              <% if post[:likes_count] > 0 %>
                <%= link_to 'view likes', get_likes_event_post_path(event_id, post.id) %>
              <% end %>
            </td>
            <td>
              <% if post[:likes_count] > 0 %>
                <%= link_to 'view comments', get_comments_event_post_path(event_id, post.id) %>
              <% end %>
            </td>
          </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</td>

app/views/shared/_user_detail.html.erb
<td class="details" colspan="6" style="background-color: lavender;">
  <div class="row">
    <div class="col-md-6">
      <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table">
        <tbody>
        <tr>
          <td><b>Gender:</b></td>
          <td><%= member_profile[:gender] || 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>DOB:</b></td>
          <td><%= member_profile[:dob] || 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>Account Type:</b></td>
          <td><%= member_profile[:account_type] || 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>High school:</b></td>
          <td><%= member_profile[:high_school] || 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>Home town:</b></td>
          <td><%= member_profile[:home_town] || 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>Contact#:</b></td>
          <td><%= member_profile[:contact_phone] || 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>Contact Add:</b></td>
          <td><%= member_profile[:contact_address] || 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>Gender:</b></td>
          <td><%= member_profile[:gender] || 'Not entered' %></td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <% if member_profile[:events_count]  || member_profile[:posts_count]  || member_profile[:followers_count]  %>
        <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table table table-striped">
          <tbody>
          <tr>
            <td>
              <%if member_profile[:events_count] %>
                <%= link_to 'view events',  user_events_user_path(member_profile[:id]) %>
              <% end %>
            </td>
            <td>
              <%if member_profile[:posts_count]  %>
                <%= link_to 'view posts',  user_posts_user_path(member_profile[:id]) %>
              <% end %>
            </td>
            <td>
              <%if member_profile[:followers_count]  %>
                <%= link_to 'view followers',  user_followers_user_path(member_profile[:id]) %>
              <% end %>
            </td>
          </tr>
          </tbody>
        </table>
      <% end %>
      <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table table table-striped">
        <tbody>
        <tr>
          <td><b>Country:</b></td>
          <td><%= member_profile[:country].present? ? member_profile[:country][:country_name] : 'Not selected' %></td>
        </tr>
        <tr>
          <td><b>City:</b></td>
          <td><%= member_profile[:city].present? ? member_profile[:city][:city_name] : 'Not selected'%></td>
        </tr>
        <tr>
          <td><b>Language:</b></td>
          <td><%= member_profile[:language].present? ? member_profile[:language][:name] : 'Not selected' %></td>
        </tr>
        <tr>
          <td><b>Religion:</b></td>
          <td><%= member_profile[:religion].present? ? member_profile[:religion][:name] : 'Not selected' %></td>
        </tr>
        <tr>
          <td><b>Ethnic background:</b></td>
          <td><%= member_profile[:ethnic_background].present? ? member_profile[:ethnic_background][:name] : 'Not entered'%></td>
        </tr>
        </tbody>
      </table>
      <table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;" class="inner-table table table-striped">
        <tbody>
        <tr>
          <td><b>College major:</b></td>
          <td><%= member_profile[:college_major].present? ? member_profile[:college_major][:name] : 'Not entered'%></td>
        </tr>
        <tr>
          <td><b>Occupation:</b></td>
          <td><%= member_profile[:occupation].present? ? member_profile[:occupation][:name] : 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>Relationship status:</b></td>
          <td><%= member_profile[:relationship_status].present? ? member_profile[:relationship_status][:name] : 'Not entered' %></td>
        </tr>
        <tr>
          <td><b>Political views:</b></td>
          <td><%= member_profile[:political_views].present? ? member_profile[:political_views][:name] : 'Not entered' %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</td>