config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  
  resources :user_sessions do
    collection do
      get 'sign_in'
    end
  end
  resources :dashboards
  resources :users, only: [:index] do
    member do
      get 'user_events'
      get 'user_posts'
      get 'user_followers'
    end
  end
  resources :posts, only:[:index]
  resources :events, only:[:index, :show] do
    resources :posts, only:[:destroy] do
      member do
        get 'get_likes'
        get 'get_comments'
        delete 'undo'
      end
      resources :post_comments, only: [:destroy]
    end
  end
  
  resources :categories
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    params[:page].present? ? page = params[:page] : page = 1
    request = {
        page:     page,
        per_page: 10,
        member_profile_id: current_profile[:id]
    }
    response_hash = api_request("posts", request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @posts       =  response.data.posts
      @paging_data = response.paging_data
    else
      return render json: false
    end
  end


  def show
    params[:page].present? ? page = params[:page] : page = 1
    request = {
        page:     page,
        per_page: 10,
        current_user_id: current_user.id
    }
    response_hash = api_request("posts/show", request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      # @event_id = params[:id]
      @posts  =  response.data.posts
      @paging_data = response.paging_data
    else
      return render json: false
    end
  end
  
  def get_likes
    params[:page].present? ? page = params[:page] : page = 1
    request = {
        page:     page,
        per_page: 10,
        post_id: params[:id]
    }
    response_hash = api_request("posts/#{params[:id]}/post_likes", request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @event_id = params[:event_id]
      @likes  =  response.data.post_likes
      @paging_data = response.paging_data
    else
      return render json: false
    end
  end
  
  def get_comments
    params[:page].present? ? page = params[:page] : page = 1
    request = {
        page:     page,
        per_page: 10,
        post_id: params[:id]
    }
    response_hash = api_request("posts/#{params[:id]}/post_comments", request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @event_id = params[:event_id]
      @post_id  = params[:id]
      @comments  =  response.data.post_comments
      @paging_data = response.paging_data
    else
      return render json: false
    end
  end
  
  def destroy
    request = {
        post_id: params[:id]
    }
    response_hash = api_request("posts/#{params[:id]}/", request, DELETE_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @event_id = params[:event_id]
      redirect_to event_path(params[:event_id])
    else
      return render json: false
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/get_comments.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li><a href="#" class="active">Post Comments</a>

      </li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="example12">
              <thead>
              <tr>
                <th></th>
                <th>Full Name</th>
                <th>Host/Co-host</th>
                <th>Comment</th>
                <th>Commented at</th>
                <th>Actions</th>
              </tr>
              </thead>
              <tbody>
              <% @comments.each do |comment| %>
                  <tr>
                    <td><i class="fa fa-plus-circle" style="margin-right:10px;"></i></td>
                    <td class="v-align-middle"><%= comment[:member_profile][:user][:first_name] + ' ' + comment[:member_profile][:user][:last_name]  %></td>
                    <td class="v-align-middle"><span class="muted"><%= comment[:is_co_host_or_host] %></span></td>
                    <td class="v-align-middle"><span class="muted"><%= comment[:post_comment] %></span></td>
                    <td class="v-align-middle"><span class="muted"><%= comment[:created_at].to_date %></span></td>
                    <td class="v-align-middle">
                      <% if comment.is_deleted %>
                          <%= link_to 'Undo', event_post_post_comment_path(@event_id, @post_id, comment.id) , class: 'btn btn-warning btn-mini', data: { confirm: 'Are you sure to undo?' }, method: 'delete' %>
                      <% else %>
                          <%= link_to 'delete', event_post_post_comment_path(@event_id, @post_id, comment.id), class: 'btn btn-danger btn-mini', data: { confirm: 'Are you sure to delete this post?' }, method: 'delete' %>
                      <% end %>
                    </td>
                  </tr>
                  <tr class="hidden"><%= render :partial => "shared/comment_detail", locals:{comment: comment} %></tr>
              <% end %>
              </tbody>
            </table>
            <%= render :partial => "shared/pagination" %>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'Go back', event_path(@event_id) , class:'btn btn-default btn-mini'%>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#example12 tbody td i').live('click', function () {
      var row = $(this).closest('tr').next('tr');
      if ($(this).hasClass('fa fa-plus-circle'))
      {
        $(this).removeClass("fa fa-plus-circle");
        $(this).addClass("fa fa-minus-circle");
        var tr = row.removeClass('hidden');
      }else{
        $(this).removeClass("fa fa-minus-circle");
        $(this).addClass("fa fa-plus-circle");
        var tr = row.addClass('hidden');
      }
    });
  })
</script>

app/views/posts/get_likes.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li><a href="#" class="active">Post Likes</a>

      </li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="example12">
              <thead>
              <tr>
                <th>Full Name</th>
                <th>Is Like?</th>
                <th>Liked at</th>
              </tr>
              </thead>
              <tbody>
              <% @likes.each do |like| %>
                  <tr>
                    <td class="v-align-middle"><%= like[:member_profile][:user][:username]  %></td>
                    <td class="v-align-middle"><span class="muted"><%= like[:like_status] %></span></td>
                    <td class="v-align-middle"><span class="muted"><%= like[:created_at].to_date %></span></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <%= render :partial => "shared/pagination" %>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'Go back', event_path(@event_id), class:'btn btn-default btn-mini'%>
  </div>
</div>

app/views/posts/index.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li><a href="#" class="active">Posts</a>

      </li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="example12">
              <thead>
              <tr>
                <th></th>
                <th>Post Title</th>
                <th>Created By</th>
                <!--<th>Is public</th>-->
                <th>Likes count</th>
                <th>Comments count</th>
                <th>Actions</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <% @posts.each do |post| %>
                  <tr>
                    <td><i class="fa fa-plus-circle" style="margin-right:10px;"></i></td>
                    <td class="v-align-middle"><%= link_to post[:post_title],posts_path(post.id) %></td>
                    <td class="v-align-middle"><%=link_to post[:member_profile][:user][:username]  %></td>
                    <!--<td class="v-align-middle"><span class="muted"><!%= post[:is_post_public] %></span></td>-->
                    <td class="v-align-middle"><%= post[:likes_count] %></td>
                    <td class="v-align-middle"><%= post[:comments_count] %></td>
                    <td class="v-align-middle">Delete</td>
                    <!--<td class="v-align-middle">-->
                      <!--<!% if post.is_deleted %>-->
                          <!--<!%= link_to 'Undo', undo_event_post_path(post.event_id, post.id) , class: 'btn btn-warning btn-mini', data: { confirm: 'Are you sure to undo?' }, method: 'delete' %>-->
                      <!--<!% else %>-->
                          <!--<!%= link_to 'delete', event_post_path(post.event_id, post.id), class: 'btn btn-danger btn-mini', data: { confirm: 'Are you sure to delete this post?' }, method: 'delete' %>-->
                      <!--<!% end %>-->
                    <!--</td>-->
                  </tr>
                  <tr class="hidden"><%= render :partial => "shared/post_detail", locals:{post: post, event_id: post.event_id} %></tr>
              <% end %>
              </tbody>
            </table>
            <%= render :partial => "shared/pagination" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#example12 tbody td i').live('click', function () {
      var row = $(this).closest('tr').next('tr');
      if ($(this).hasClass('fa fa-plus-circle'))
      {
        $(this).removeClass("fa fa-plus-circle");
        $(this).addClass("fa fa-minus-circle");
        var tr = row.removeClass('hidden');
      }else{
        $(this).removeClass("fa fa-minus-circle");
        $(this).addClass("fa fa-plus-circle");
        var tr = row.addClass('hidden');
      }
    });
  })
</script>

app/views/posts/show.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li><a href="#" class="active">Event Posts</a>

      </li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="example12">
              <thead>
              <tr>
                <th></th>
                <th>Post Title</th>
                <th>Created By</th>
                <th>Is public</th>
                <th>Likes count</th>
                <th>Comments count</th>
                <th>Actions</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <% @posts && @posts.each do |post| %>
                  <tr>
                    <td><i class="fa fa-plus-circle" style="margin-right:10px;"></i></td>
                    <td class="v-align-middle"><%= link_to post[:post_title],post_path(post.id) %></td>
                    <td class="v-align-middle"><%=link_to "#{post[:member_profile][:user][:username]}", '#' %></td>
                    <td class="v-align-middle"><span class="muted"><%= post[:is_post_public] %></span></td>
                    <td class="v-align-middle"><%= post[:likes_count] %></td>
                    <td class="v-align-middle"><%= post[:comments_count] %></td>
                    <td class="v-align-middle">
                      <% if post.is_deleted %>
                          <%= link_to 'Undo', undo_event_post_path(@event_id, post.id) , class: 'btn btn-warning btn-mini', data: { confirm: 'Are you sure to undo?' }, method: 'delete' %>
                      <% else %>
                          <%= link_to 'delete', event_post_path(@event_id, post.id), class: 'btn btn-danger btn-mini', data: { confirm: 'Are you sure to delete this post?' }, method: 'delete' %>
                      <% end %>
                    </td>
                  </tr>
                  <tr class="hidden"><%= render :partial => "shared/post_detail", locals:{post: post, event_id: @event_id} %></tr>
              <% end %>
              </tbody>
            </table>
            <%= render :partial => "shared/pagination" %>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'Go back', posts_path, class:'btn btn-default btn-mini' %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#example12 tbody td i').live('click', function () {
      var row = $(this).closest('tr').next('tr');
      if ($(this).hasClass('fa fa-plus-circle'))
      {
        $(this).removeClass("fa fa-plus-circle");
        $(this).addClass("fa fa-minus-circle");
        var tr = row.removeClass('hidden');
      }else{
        $(this).removeClass("fa fa-minus-circle");
        $(this).addClass("fa fa-plus-circle");
        var tr = row.addClass('hidden');
      }
    });
  })
</script>