config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  
  resources :user_sessions do
    collection do
      get 'sign_in'
    end
  end
  resources :dashboards
  resources :users, only: [:index] do
    member do
      get 'user_events'
      get 'user_posts'
      get 'user_followers'
    end
  end
  resources :posts, only:[:index]
  resources :events, only:[:index, :show] do
    resources :posts, only:[:destroy] do
      member do
        get 'get_likes'
        get 'get_comments'
        delete 'undo'
      end
      resources :post_comments, only: [:destroy]
    end
  end
  
  resources :categories
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    if params[:page].present?
      page = params[:page]
    else
      page = 1
    end
    request = {
        page:     page,
        per_page: 10,
        auth_token: current_profile[:auth_token]
    }
    response_hash = api_request('categories', request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @categories    = response.data.categories
    else
      return render json: false
    end
  end
  
  def create
    if params[:name].present?
      request = {
          category: {
              name: params[:name]
          }
      }
      response_hash = api_request('categories', request, POST_REQUEST, true)
      response      = HashToObject.convert(response_hash)
      if response.resp_status == 1
        redirect_to  categories_path
      else
        return render json: false
      end
    else
      redirect_to categories_path
    end
  end
  
  def edit
    request = {}
    response_hash = api_request("categories/#{params[:id]}/edit", request, GET_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      @category = response.data.category
    else
      return render json: false
    end
  end
  
  def update
    if params[:name].present?
      request = {
          name: params[:name]
      }
      response_hash = api_request("/categories/#{params[:id]}", request, PUT_REQUEST, true)
      response      = HashToObject.convert(response_hash)
      if response.resp_status == 1
        redirect_to  categories_path
      else
        return render json: false
      end
    else
      redirect_to categories_path
    end
  end
  
  
  def destroy
    request = {}
    response_hash = api_request("categories/#{params[:id]}", request, DELETE_REQUEST, true)
    response      = HashToObject.convert(response_hash)
    if response.resp_status == 1
      redirect_to  categories_path
    else
      return render json: false
    end
  end
  
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li>
        <a href="#" class="active">Categories / Edit</a>
      </li>
    </ul>
    <div style="margin-bottom: 7px;">
      <%= form_tag category_path(@category.id), :method => :put  do %>
        <div class="form-group">
          <%= text_field_tag(:name, @category.name) %>
        </div>
          <%= link_to "Back", categories_path, class:'btn btn-default btn-mini' %>
          <%= submit_tag "Done", class:'btn btn-primary btn-mini' %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body">Widget settings form goes here</div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <ul class="breadcrumb">
      <li>
        <p>YOU ARE HERE</p>
      </li>
      <li>
        <a href="#" class="active">Categories</a>
      </li>
    </ul>
    <div class="pull-right" style="margin-bottom: 7px;">
      <form action="/categories" method="post" class="form-inline">
        <div class="form-group">
          <input type="text" class="form-control" name="name" placeholder="Category name">
        </div>
        <button type="submit" class="btn btn-default">Save</button>
      </form>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="grid simple ">
          <div class="grid-body no-border">
            <table class="table no-more-tables" id="edit-category">
              <thead>
              <tr>
                <th>Sr#</th>
                <th>Name</th>
                <th>Actions</th>

              </tr>
              </thead>
              <tbody>
              <% @categories.each_with_index do |category,index| %>
                  <tr>
                    <td><%= "#{index + 1}" %></td>
                    <td class="v-align-middle"><%= category[:name] %></td>
                    <td class="v-align-middle">
                      <%= link_to 'edit', edit_category_path(category.id),   class: 'btn btn-primary btn-mini' %>
                      <% if category.is_deleted %>
                          <%= link_to 'undo', category_path(category.id), class: 'btn btn-warning btn-mini', data: { confirm: 'Are you sure to undo this category?' }, method: 'delete' %>
                      <% else %>
                          <%= link_to 'delete', category_path(category.id), class: 'btn btn-danger btn-mini', data: { confirm: 'Are you sure to delete this category?' }, method: 'delete' %>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>